# Generated by Django 3.2.4 on 2021-07-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaApp1', '0002_categoria_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activada / No Activada'),
        ),
        migrations.AddField(
            model_name='producto',
            name='Publicado',
            field=models.BooleanField(default=True, verbose_name='Publicado / No Publicado'),
        ),
    ]
